sudo: required
services: 
  - docker
before_install:
  -  docker build -t alfalavi/docker-react -f Dockerfile.dev .

script:
  - docker run alfalavi/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "travis"
  env: "Travis-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-244815535546"
  bucket_path: "travis"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure:  "$AWS_SECRET_KEY"
